name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Clean install of dependencies
        pip uninstall -y numpy pandas scikit-learn
        pip cache purge
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: project-demo-1-439713
        export_default_credentials: true

    - name: Run Data Processing
      run: python data_processing.py

    - name: Evaluate Model
      id: evaluate
      run: |
        echo "Starting model evaluation..."
        rm -f /tmp/model.pkl
    
        # Run evaluation and capture output
        EVAL_OUTPUT=$(python evaluate_model.py 2>&1)
        echo "Evaluation output:"
        echo "$EVAL_OUTPUT"
    
        # Check for errors or retraining conditions
        if echo "$EVAL_OUTPUT" | grep -q "ModuleNotFoundError\|ImportError\|Accuracy below threshold\|No existing model found"; then
          echo "Retraining condition met - setting RETRAIN=true"
          echo "RETRAIN=true" >> $GITHUB_ENV
        else
          echo "Model accuracy meets threshold - no retraining needed"
        fi


    - name: Trigger Retraining
      if: env.RETRAIN == 'true'
      run: |
        echo "Starting retraining process..."
        ACCESS_TOKEN=$(gcloud auth print-identity-token)
        curl -X POST \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          --max-time 30 \
          --verbose \
          https://us-east4-project-demo-1-439713.cloudfunctions.net/retrain_model

    - name: Build and Push Docker Image
      if: env.RETRAIN == 'true'
      env:
        PROJECT_ID: project-demo-1-439713
        REGION: us-east4
        REPOSITORY: model-docker-registry
      run: |
        echo "Starting Docker build and push..."
        gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/model:latest .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/model:latest