name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-project-id
        export_default_credentials: true

    - name: Run Data Processing
      run: python data_processing.py

    - name: Evaluate Model
      id: evaluate
      continue-on-error: true
      run: |
        echo "Starting model evaluation..."
        EVAL_OUTPUT=$(python evaluate_model.py 2>&1)
        echo "Evaluation output:"
        echo "$EVAL_OUTPUT"
        if echo "$EVAL_OUTPUT" | grep -q "Accuracy below threshold\|No existing model found"; then
          echo "Retraining condition met - setting RETRAIN=true"
          echo "RETRAIN=true" >> $GITHUB_ENV
          exit 1
        else
          echo "Model accuracy meets threshold - no retraining needed"
        fi

    - name: Trigger Retraining
      if: env.RETRAIN == 'true'
      run: |
        echo "Starting retraining process..."
        ACCESS_TOKEN=$(gcloud auth print-identity-token)
        RESPONSE=$(curl -X POST \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          --max-time 30 \
          --verbose \
          https://us-east4-project-demo-1-439713.cloudfunctions.net/retrain_model)
        echo "Cloud Function Response:"
        echo "$RESPONSE"

    - name: Build and Push Docker Image
      if: env.RETRAIN == 'true'
      env:
        PROJECT_ID: project-demo-1-439713
        REGION: us-east4
        REPOSITORY: model-docker-registry
      run: |
        echo "Starting Docker build and push..."
        echo "Project ID: $PROJECT_ID"
        echo "Region: $REGION"
        echo "Repository: $REPOSITORY"
        
        echo "Checking GCP authentication..."
        gcloud auth list
        
        # Configure docker with verbose logging
        gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
        
        # Build with verbose output
        echo "Building Docker image..."
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/model:latest . --progress=plain
        
        # Push with verbose output
        echo "Pushing Docker image..."
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/model:latest --verbose